# Generated by Django 5.2.16 on 2026-07-30 18:13

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('sale_code', models.CharField(max_length=32, unique=True, verbose_name='Mã giao dịch')),
                ('sold_at', models.DateTimeField(db_index=True, verbose_name='Thời điểm bán')),
                ('subtotal', models.PositiveBigIntegerField(verbose_name='Tổng tiền trước giảm')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='Số tiền giảm')),
                ('final_total', models.PositiveBigIntegerField(verbose_name='Tổng tiền thực tế')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản'), ('other', 'Khác')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='completed', max_length=20, verbose_name='Trạng thái')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hủy')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Lý do hủy')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Giao dịch',
                'ordering': ('-sold_at', '-id'),
                'indexes': [models.Index(fields=['status', 'sold_at'], name='sale_status_sold_at_idx'), models.Index(fields=['payment_method', 'sold_at'], name='sale_payment_sold_at_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='sale_subtotal_non_negative'), models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='sale_discount_non_negative'), models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('subtotal'))), name='sale_discount_not_greater_than_subtotal'), models.CheckConstraint(condition=models.Q(('final_total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('discount_amount')))), name='sale_final_total_consistent'), models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('status', 'completed')), models.Q(('cancelled_at__isnull', False), ('status', 'cancelled')), _connector='OR'), name='sale_cancellation_state_consistent')],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('category_name_snapshot', models.CharField(max_length=120, verbose_name='Loại mặt hàng')),
                ('size_snapshot', models.CharField(max_length=50, verbose_name='Size')),
                ('color_snapshot', models.CharField(blank=True, max_length=120, verbose_name='Màu sắc')),
                ('sku_snapshot', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('listed_price', models.PositiveBigIntegerField(verbose_name='Giá niêm yết')),
                ('actual_unit_price', models.PositiveBigIntegerField(verbose_name='Giá bán thực tế')),
                ('unit_cost_snapshot', models.PositiveBigIntegerField(verbose_name='Giá vốn tại thời điểm bán')),
                ('line_total', models.PositiveBigIntegerField(verbose_name='Thành tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.productvariant', verbose_name='Biến thể sản phẩm')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.sale', verbose_name='Giao dịch')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong giao dịch',
                'verbose_name_plural': 'Sản phẩm trong giao dịch',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['sale'], name='sale_item_sale_idx'), models.Index(fields=['product_variant'], name='sale_item_variant_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_item_quantity_positive'), models.CheckConstraint(condition=models.Q(('listed_price__gte', 0)), name='sale_item_listed_price_non_negative'), models.CheckConstraint(condition=models.Q(('actual_unit_price__gte', 0)), name='sale_item_actual_price_non_negative'), models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__gte', 0)), name='sale_item_unit_cost_non_negative'), models.CheckConstraint(condition=models.Q(('line_total', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('actual_unit_price')))), name='sale_item_line_total_consistent')],
            },
        ),
    ]
