# Generated by Django 5.2.16 on 2026-07-30 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('cost_price_pin_hash', models.CharField(blank=True, max_length=256, verbose_name='Hash mã PIN giá vốn')),
                ('cost_price_lock_timeout_minutes', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Thời gian tự khóa (phút)')),
            ],
            options={
                'verbose_name': 'Thiết lập bảo mật shop',
                'verbose_name_plural': 'Thiết lập bảo mật shop',
                'constraints': [models.CheckConstraint(condition=models.Q(('cost_price_lock_timeout_minutes__gte', 1), ('cost_price_lock_timeout_minutes__lte', 120)), name='security_timeout_between_1_and_120')],
            },
        ),
    ]
