# Generated by Django 5.2.16 on 2026-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_idempotencyrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsecuritysettings",
            name="revision",
            field=models.PositiveBigIntegerField(
                default=1, editable=False, verbose_name="Phiên bản bản ghi"
            ),
        ),
    ]
