# Generated by Django 5.2.16 on 2026-07-30 18:13

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=120, verbose_name='Tên loại mặt hàng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Loại mặt hàng',
                'verbose_name_plural': 'Loại mặt hàng',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_case_insensitive_unique')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='Thương hiệu')),
                ('color', models.CharField(blank=True, max_length=120, verbose_name='Màu sắc')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/', verbose_name='Ảnh sản phẩm')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Loại mặt hàng')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('size', models.CharField(max_length=50, verbose_name='Size')),
                ('sku', models.CharField(blank=True, default='', max_length=100, verbose_name='SKU')),
                ('cost_price', models.PositiveBigIntegerField(default=0, verbose_name='Giá vốn')),
                ('selling_price', models.PositiveBigIntegerField(default=0, verbose_name='Giá bán')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng')),
                ('low_stock_threshold', models.PositiveIntegerField(default=2, verbose_name='Ngưỡng sắp hết')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
                'ordering': ('product__name', 'size'),
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('initial', 'Tồn kho ban đầu'), ('import', 'Nhập thêm hàng'), ('sale', 'Bán hàng'), ('sale_return', 'Hoàn tồn khi hủy giao dịch'), ('adjustment', 'Điều chỉnh thủ công')], max_length=20, verbose_name='Loại biến động')),
                ('quantity_before', models.PositiveIntegerField(verbose_name='Số lượng trước')),
                ('quantity_change', models.IntegerField(verbose_name='Số lượng thay đổi')),
                ('quantity_after', models.PositiveIntegerField(verbose_name='Số lượng sau')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='Loại tham chiếu')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='Mã tham chiếu')),
                ('note', models.TextField(verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='catalog.productvariant', verbose_name='Biến thể sản phẩm')),
            ],
            options={
                'verbose_name': 'Biến động tồn kho',
                'verbose_name_plural': 'Biến động tồn kho',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'active'], name='product_category_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['active', 'quantity'], name='variant_active_quantity_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['size'], name='variant_size_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='variant_sku_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('size'), models.F('product'), name='variant_product_size_case_insensitive_unique'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), condition=models.Q(('sku', ''), _negated=True), name='variant_sku_case_insensitive_unique'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='variant_cost_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='variant_selling_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='variant_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='variant_low_stock_threshold_non_negative'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product_variant', '-created_at'], name='movement_variant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='movement_reference_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_before__gte', 0)), name='movement_quantity_before_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_after__gte', 0)), name='movement_quantity_after_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_after', django.db.models.expressions.CombinedExpression(models.F('quantity_before'), '+', models.F('quantity_change')))), name='movement_quantities_consistent'),
        ),
    ]
