# Generated by Django 5.2.16 on 2026-07-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbnails/', verbose_name='Ảnh thu nhỏ'),
        ),
    ]
