# Generated by Django 5.2.16 on 2026-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="revision",
            field=models.PositiveBigIntegerField(
                default=1, editable=False, verbose_name="Phiên bản bản ghi"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="revision",
            field=models.PositiveBigIntegerField(
                default=1, editable=False, verbose_name="Phiên bản bản ghi"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="revision",
            field=models.PositiveBigIntegerField(
                default=1, editable=False, verbose_name="Phiên bản bản ghi"
            ),
        ),
    ]
